services:
  firelord-db:
    image: postgres:16-alpine
    container_name: firelord-db
    environment:
      POSTGRES_DB: ${DB_NAME:-firelord}
      POSTGRES_USER: ${DB_USER:-firelord}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-firelord}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
